### ISSUE TITLE
Smaller/square-ish logos have dragging artifact in game view

### ISSUE THREAD

**Issue by cnapolit** [seannuh/McHERO#3]
During the intro horizontal slide animation, small/square logos can have some artifacting upon initial viewing during the opening animations.
I have not observed this issue with the more typical larger logos.
https://user-images.githubusercontent.com/94765074/216738464-390cd7c8-9910-42bd-82ae-f6f736eb5586.mp4

**Comment by seannuh** [comment]
Another interesting one that I can't see on my end. It must be something due to the two different animations within that grid, the left to right one for the icons and the up and down one for the entire grid. I might have to move some things around to avoid this but not sure when I'll get to it.

**Comment by cnapolit** [comment]
No worries, this kind of thing is really just to track it.

**Comment by seannuh** [comment]
I believe I was able to fix this with update 1.0.8, please let me know otherwise.
