### ISSUE TITLE
The geometry of the left game options/info UI element can be visible against darker videos

### ISSUE THREAD

**Issue by cnapolit** [seannuh/McHERO#4]
Inside the game details view while a video is playing, a black UI element can be seen that will slide in and out of view when a video is focused/unfocused during particularly dark sections (which happen to occur pretty often at the start).
Not a huge issue, but likely impossible to notice in some setups so I figured I would mention it.

Recordings don't seem to capture it and some monitors might not even show it.
This effect is at least visible on an OLED display.

**Comment by seannuh** [comment]
Hm hard to say what might be causing this since I don't have an OLED screen and am not seeing it on my end. I have a feeling it's caused by the black gradient that slides in and out when the zoom button is pushed.
