### ISSUE TITLE
Adding background video for Cover art (not image background) for theme J-hero

### ISSUE THREAD

**Issue by WilliamLeGod** [seannuh/McHERO#5]
OMG Bro! I love this J-hero theme so much especially the animation when navigating between game is so freaking smooth!
I really love the video background feature for cover art image so if u could spend some time adding it, I would be much appreciated.

Anyway, thanks for yr hard work!

**Comment by blackxored** [comment]
Bumping this. Having video in the details page looks really really nice

**Comment by seannuh** [comment]
I actually added this to McHERO so Jhanlon95 would need to add it to his fork to be in J-Hero. https://github.com/Jhanlon95/J-Hero
