### ISSUE TITLE
Visible filter presets off screen when filter is empty

### ISSUE THREAD

**Issue by cnapolit** [seannuh/McHERO#6]
If the list of games is empty for a filter, the set of visible filter presets ends up off-screen. They can still be interacted with, but which filter is selected is hard to know without visual confirmation.

https://github.com/seannuh/McHERO/assets/94765074/eb865680-a147-4fec-87bb-d7a03fc064c5

**Comment by seannuh** [comment]
Gross!! I'll look into this for sure. Thanks so much for the video.

**Comment by seannuh** [comment]
Ok solved this. Weird leftover datatriggers that were never really necessary. Will be pushed out in next update.

**Comment by cnapolit** [comment]
Dang, fastest fix in the west. Nice job!
