### ISSUE TITLE
[Request] SuccessStory achievements fix

### ISSUE THREAD

**Issue by blackxored** [seannuh/McHERO#7]
I've noticed SuccessStory's achievements appear in black. Anything we can do to fix?

![image](https://github.com/seannuh/McHERO/assets/133308/af782ac9-8bc1-4222-bb53-95fa4d3bf46f)

**Comment by seannuh** [comment]
Unfortunately, there are some limitations to most extensions in fullscreen mode, so there's no real way I've found to change the color of that text.

**Comment by blackxored** [comment]
I was able to get that line by adding

```
<Color x:Key="TextColorDarker">#a3a3a3</Color>
<SolidColorBrush x:Key="TextBrushDarker" Color="{DynamicResource TextColorDarker}" />
```

to `Constants.xaml` in the theme. But I've no idea what I'm doiing as this is the first time I look into themes at all. I wasn't able to fix the black bars and black total.
