### ISSUE TITLE
May I ask for your help

### ISSUE THREAD

**Issue by Itachi0833** [seannuh/McHERO#8]
Hello, your topic is great, but I need your help to solve another issue with another topic. You understand the code, could you please help me check the issue of PS5ish's description box not being able to drop down in the new version of Playnite?

**Comment by seannuh** [comment]
Sorry but I barely have time to work on my own theme at the moment so I don't think I'd have time to help you out there. You could try the Playnite Discord to see if anyone there could help you out though.
